#!/bin/bash

# This script does a distribution upgrade and updates flatpaks
# for OpenSUSE Tumbleweed installations

# Install instructions:
# - place this file, update-system, in /home/[YOURNAME]/bin/
# - set update-system as executable
# How to use:
# - run update-system on the terminal and follow the instructions

# check for internet before attempting to continue
echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1

if [ $? -eq 1 ]; then
    echo "This device is offline. Please connect to the internet and try again."; exit;
fi

original_snap_version="$( lsb-release -r )"

if [ "$original_snap_version" == "" ]; then
    echo "Error: Cannot get current snapshot version. Make sure lsb-release is installed properly and try again."; exit;
fi

echo "---Current Snapshot---" &&
echo $original_snap_version &&
echo "---Stopping Packagekit---" &&
sudo systemctl stop packagekit &&
echo "---Running System Upgrade---" &&
sudo zypper dup &&
echo "---Updating Flatpaks---" &&
flatpak update &&
echo "---Updating Snap Packages---" &&
sudo snap refresh &&
echo "---Updates Finished---" &&
final_snap_version="$( lsb-release -r )" &&

if [[ "$original_snap_version" == "$final_snap_version" ]]; then
    echo "Snapshot has not changed. A reboot is likely unnecessary."
else
    echo -e "Snapshot has been upgraded to:\n$final_snap_version"
    read -p "It is recommended to reboot after a system upgrade. Do you want to reboot? [y/n] (y)" yn
    case $yn in
        [Yy]* ) echo "Rebooting"; /usr/sbin/reboot;;
        "" ) echo "Rebooting"; /usr/sbin/reboot;;
        * ) exit;;
    esac

fi
